### ISSUE TITLE
How to set environment for alertmanager2es ?

### ISSUE THREAD

**Issue by SAbdulRahuman** [cloudflare/alertmanager2es#16]
Hi ,
I need to use alertmanager2es using docker, is there any example to set environment variable to alertmanager2es like addr, port, and etc ?.

**Comment by Dhyanesh97** [comment]
I am also struggling to setup an docker for alertmanager2es. 
Is there any proper doc for it ?
Also I need to send alerts to elastic cloud so, can you provide any additional info about it 

I have added below lines to docker but doesn't seems to be working

```
alertmanagere2e:
    image: webdevops/alertmanager2es
    container_name: alertmanagere2e
    restart: always
    networks:
      - analytics
    ports:
      - "9097:9097"
    command: ./alertmanager2es --elasticsearch.address="url:port/" --elasticsearch.username="username" --elasticsearch.password="password" --elasticsearch.index="alertmanager-2" 
```
